### ISSUE TITLE
Helm Chart repo

### ISSUE THREAD

**Issue by kladiv** [mecodia/cert-manager-webhook-hetzner#3]
Hello,
can you provide an helm repo for the installation? Via GitHub Pages or https://artifacthub.io/
We use k3s Helm Controller to install charts in our K8S infrastructure. We're evaluating to move off the forked one (it seems not up-to-date)

Thank you

**Comment by ArgonQQ** [comment]
Would also appreciate that!

**Comment by toabi** [comment]
You can use https://mecodia.github.io/cert-manager-webhook-hetzner/ as helm repository.

**Comment by yelhouti** [comment]
@toabi It would be great to change the README to reflect this, instead of telling others to clone :)
