### ISSUE TITLE
Cannot install Webhook - deploy not found

### ISSUE THREAD

**Issue by realulim** [mecodia/cert-manager-webhook-hetzner#5]
The installation instructions state:

`helm install --namespace kube-system cert-manager-webhook-hetzner ./deploy/cert-manager-webhook-hetzner`

However, there is no "deploy" subdirectory anywhere in the repository.

**Comment by toabi** [comment]
Sorry for late reply, but the path to the chart should be `./cert-manager-webhook-hetzner` - this repository needs some more ❤️
